Exclude desktop dist files from dup check

diff --git a/.github/workflows/sonar_coverage.yml b/.github/workflows/sonar_coverage.yml
--- a/.github/workflows/sonar_coverage.yml
+++ b/.github/workflows/sonar_coverage.yml
@@ -41,7 +41,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: "3.11"
 
       - name: Install test requirements
         run: |
@@ -58,14 +58,13 @@ jobs:
           coverage report -m
           coverage xml -o tests/python/coverage/agent/coverage.xml
 
-
       - name: Upload Agent coverage
         uses: actions/upload-artifact@v4
         with:
           name: agent-coverage
           path: tests/python/coverage/agent/coverage.xml
           if-no-files-found: warn
-# ThreatDetection Python tests
+  # ThreatDetection Python tests
   test_threat_detection:
     runs-on: ubuntu-latest
     steps:
@@ -75,7 +74,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: "3.11"
 
       - name: Install test requirements
         run: |
@@ -112,7 +111,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: "3.11"
 
       - name: Install test requirements
         run: |
@@ -154,7 +153,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: "3.11"
 
       - name: Install test requirements
         run: |
@@ -196,7 +195,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '18'
+          node-version: "18"
 
       - name: Install DesktopUI dependencies
         working-directory: cloudshield/DesktopUI
@@ -232,7 +231,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '18'
+          node-version: "18"
 
       - name: Install WebUI dependencies
         working-directory: cloudshield/WebUI
@@ -261,7 +260,16 @@ jobs:
   # Sonar scan (runs AFTER all tests finish)
   sonar_scan:
     runs-on: ubuntu-latest
-    needs: [test_agent, test_server, test_cloud, test_threat_detection, test_desktopui, test_webui, retrieve_branch]
+    needs:
+      [
+        test_agent,
+        test_server,
+        test_cloud,
+        test_threat_detection,
+        test_desktopui,
+        test_webui,
+        retrieve_branch,
+      ]
     steps:
       - name: Checkout Code with Full History
         uses: actions/checkout@v4
@@ -329,7 +337,8 @@ jobs:
             -Dsonar.coverage.exclusions=**/tests/**,**/WebUI/babel.config.cjs,**/WebUI/src/main.jsx,**/WebUI/src/App.jsx,**/WebUI/jest.config.cjs,**/WebUI/jest.setup.js,**/__tests__/**,cloudshield/**/templates/**/*.tf,cloudshield/Cloud/templates/**/*.tf,cloudshield/**/agent_pb2.py,cloudshield/**/agent_pb2_grpc.py,cloudshield/**/*_pb2.py,cloudshield/**/*_pb2_grpc.py,cloudshield/**/logger.py,**/*.html,**/bootstrap/**,**/__init__.py,**/docker_provisioner/**,**.sh \
             -Dsonar.exclusions=**/tests/**,**/__tests__/**,**/WebUI/src/main.jsx,**/WebUI/src/App.jsx,**/WebUI/babel.config.cjs,**/WebUI/jest.config.cjs,**/WebUI/jest.setup.js,cloudshield/**/templates/**/*.tf,cloudshield/Cloud/templates/**/*.tf,cloudshield/**/agent_pb2.py,cloudshield/**/agent_pb2_grpc.py,cloudshield/**/*_pb2.py,cloudshield/**/*_pb2_grpc.py,cloudshield/**/logger.py,**/*.html,**/bootstrap/**,**/__init__.py,**/docker_provisioner/**,**.sh \
             -Dsonar.python.coverage.reportPaths=tests/python/coverage/agent/coverage.xml,tests/python/coverage/server/coverage.xml,tests/python/coverage/cloud/coverage.xml,tests/python/coverage/threat_detection/coverage.xml,*.html \
-            -Dsonar.javascript.lcov.reportPaths=tests/js/coverage/desktopui/lcov.info,tests/js/coverage/webui/lcov.info || (echo "SonarCloud analysis failed" && exit 1)
+            -Dsonar.javascript.lcov.reportPaths=tests/js/coverage/desktopui/lcov.info,tests/js/coverage/webui/lcov.info || (echo "SonarCloud analysis failed" && exit 1) \
+            -Dsonar.cpd.exclusions=**/DesktopUI/dist-electron/**
 
       - name: Get SonarCloud Results
         run: "echo 'Check SonarCloud Report: https://sonarcloud.io/summary/new_code?id=ACCISA_CloudShield&branch=${GITHUB_REF##*/}'"
