adding more specifications to the sonarcloud

diff --git a/.github/workflows/sonar_coverage.yml b/.github/workflows/sonar_coverage.yml
--- a/.github/workflows/sonar_coverage.yml
+++ b/.github/workflows/sonar_coverage.yml
@@ -1,6 +1,6 @@
 name: CI + Sonar Coverage Analysis
 
-on: [pull_request]
+on: [push, pull_request]
 
 permissions:
   contents: read
@@ -169,22 +169,19 @@ jobs:
           echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH
 
       - name: Run SonarCloud Analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_ORG: ${{ secrets.SONAR_ORG }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
+          export PATH="/opt/sonar-scanner/bin:$PATH"
           sonar-scanner \
-            -Dsonar.organization=${SONAR_ORG} \
-            -Dsonar.projectKey=my-org_my-project \
+            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
+            -Dsonar.projectKey=ACCISA_CloudShield \
             -Dsonar.sources=cloudshield \
-            -Dsonar.host.url=${SONAR_HOST_URL} \
-            -Dsonar.login=${SONAR_TOKEN} \
+            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
+            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
             -Dsonar.coverage.exclusions=tests/**,cloudshield/**/agent_pb2.py,cloudshield/**/agent_pb2_grpc.py,cloudshield/**/logger.py \
             -Dsonar.exclusions=tests/**,cloudshield/**/agent_pb2.py,cloudshield/**/agent_pb2_grpc.py,cloudshield/**/logger.py \
             -Dsonar.python.coverage.reportPaths=tests/python/coverage/agent/coverage.xml,tests/python/coverage/server/coverage.xml \
-            -Dsonar.javascript.lcov.reportPaths=tests/js/coverage/desktopui/lcov.info || true
-
+            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info || (echo "SonarCloud analysis failed" && exit 1)
+      
       - name: Get SonarCloud Results
         run: "echo 'Check SonarCloud Report: https://sonarcloud.io/summary/new_code?id=ACCISA_CloudShield&branch=${GITHUB_REF##*/}'"
 
